type ActionStrings = 'blacklistedLink'
  | 'capsSpam'
  | 'emoteSpam'
  | 'externalLink'
  | 'massPings'
  | 'profanity'
  | 'repeatedText'
  | 'spoilerSpam'
  | 'zalgo'
  | 'hoistUsername'
  | 'hoistNickname'
